spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testproject
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    user:
      name: users
      password: 1234
      roles: ADMIN
    oauth2:
      client:
        registration:
          google:
            client-id: 132411150152-5vlmaijljnl372ogd3rmd70du2grklcn.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gamil.com
  secret_key: study-springboot

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disalbe-swagger-default-url: true

  # request type 기본 값
  default-cunsumes-media-type: application/json
  # response type 기본 값
  default-produces-media-type: application/json
